export const sexdata = ["Male", "Female"];

export const civilStatus = ["Single", "Married", "Divorced", "Widow", "Separated"];

export const selection = ["Yes", "No"];

export const housestatus = ["House Owner", "Renter", "Sharer"];

export const areas = [
  "Purok 1, Sitio 1",
  "Purok 2, Sitio 1",
  "Purok 3, Sitio 1",
  "Purok 4, Sitio 1",
  "Purok 5, Sitio 1",
  "Purok 6, Sitio 1",
  "Purok 7, Sitio 1",
  "Purok 8, Sitio 1",
  "Purok 9, Sitio 1",
  "Purok 10, Sitio 1",
  "Purok 1, Sitio 2",
  "Purok 2, Sitio 2",
  "Purok 3, Sitio 2",
  "Purok 4, Sitio 2",
  "Purok 5, Sitio 2",
  "Purok 6, Sitio 2",
  "Purok 7, Sitio 2",
  "Purok 8, Sitio 2",
  "Purok 9, Sitio 2",
  "Purok 10, Sitio 2",
  "Purok 1, Sitio 3",
  "Purok 2, Sitio 3",
  "Purok 3, Sitio 3",
  "Purok 4, Sitio 3",
  "Purok 5, Sitio 3",
  "Purok 6, Sitio 3",
  "Purok 7, Sitio 3",
  "Purok 8, Sitio 3",
  "Purok 9, Sitio 3",
  "Purok 10, Sitio 3",
  "Purok 1, Sitio 4",
  "Purok 2, Sitio 4",
  "Purok 3, Sitio 4",
  "Purok 4, Sitio 4",
  "Purok 5, Sitio 4",
  "Purok 6, Sitio 4",
  "Purok 7, Sitio 4",
  "Purok 8, Sitio 4",
  "Purok 9, Sitio 4",
  "Purok 10, Sitio 4",
  "Purok 1, Sitio 5",
  "Purok 2, Sitio 5",
  "Purok 3, Sitio 5",
  "Purok 4, Sitio 5",
  "Purok 5, Sitio 5",
  "Purok 6, Sitio 5",
  "Purok 7, Sitio 5",
  "Purok 8, Sitio 5",
  "Purok 9, Sitio 5",
  "Purok 10, Sitio 5",
  "Purok 1, Sitio 6",
  "Purok 2, Sitio 6",
  "Purok 3, Sitio 6",
  "Purok 4, Sitio 6",
  "Purok 5, Sitio 6",
  "Purok 6, Sitio 6",
  "Purok 7, Sitio 6",
  "Purok 8, Sitio 6",
  "Purok 9, Sitio 6",
  "Purok 10, Sitio 6"
];
